spring:
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
  application:
    name: rag-remote-embedding

  ai:
    dashscope:
      api-key: { 阿里云百炼平台申请的API Key }
    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530
          username: root
          password: milvus
        databaseName: default
        collectionName: alibaba
        embeddingDimension: 1536
        indexType: IVF_FLAT
        metricType: COSINE

server:
  port: 1818
  tomcat:
    max-http-form-post-size: 20MB

zilliz:
    username: root
    password: milvus
    endpoint: http://localhost:19530



